tensorboard: True
random_seed: 42

target_model: diffusion # valid model: diffusion, vae
dataset: celeba # valid dataset: celeba, tiny-in
attack_kind: stat # valid attacks: nn, stat
loss_kind: ddpm # valid loss estimation methods: ddpm, ddim
time_step: 10
time_sec: 100
calibration: true # whether to enable calibration
sample_number: 100 # the number of samples for each data group
eval_batch_size: 100 # batch size of the evaluation phase
diffusion_sample_number: 10 # the number of equidistant sampling
perturbation_number: 10 # the number of query
attack_data_path: attack
#
epoch_number: 50
load_trained: False # whether to load existing trained attack model
load_attack_data: false # whether to load prepared attack data if existing.
split: [123123, 3213]