tensorboard: True
random_seed: 42

target_model: diffusion # valid model: diffusion, vae
dataset: celeba # valid dataset: celeba, tinyin
attack_kind: stat # valid attacks: nn, stat
loss_kind: ddpm # valid loss estimation methods: ddpm, ddim
time_step: 10
time_sec: 100
calibration: true # whether to enable calibration
sample_number: 1000 # the number of samples for each data group
eval_batch_size: 100 # batch size of the evaluation phase
diffusion_sample_number: 10 # the number of equidistant sampling
diffusion_sample_steps: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450] # the sample steps of diffusion model
perturbation_number: 10 # the number of query
extensive_per_num: 10 # sample number, should be set 1 for diffusion models
start_strength: 0.95 # start strength factor of the perturbation mechanism
end_strength: 0.7 # end strength factor of the perturbation mechanism
attack_data_path: attack
#
epoch_number: 1000
load_trained: true # whether to load existing trained attack model
load_attack_data: true # whether to load prepared attack data if existing.
split: [123123, 3213]